/* Generated by MyraPad at 3/16/2021 11:46:25 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;

#if MONOGAME || FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#elif STRIDE
using Stride.Core.Mathematics;
#else
using System.Drawing;
using System.Numerics;
#endif

namespace GMRTSClient.UI
{
	partial class GameUI: Panel
	{
		private void BuildUI()
		{
			moveButton = new MenuItem();
			moveButton.Text = "Move";
			moveButton.Id = "moveButton";

			attackButton = new MenuItem();
			attackButton.Text = "Attack";
			attackButton.Id = "attackButton";

			assistButton = new MenuItem();
			assistButton.Text = "Assist";
			assistButton.Id = "assistButton";

			patrolButton = new MenuItem();
			patrolButton.Text = "Patrol";
			patrolButton.Id = "patrolButton";

			buildButton = new MenuItem();
			buildButton.Text = "Build";
			buildButton.Id = "buildButton";

			var horizontalMenu1 = new HorizontalMenu();
			horizontalMenu1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			horizontalMenu1.Items.Add(moveButton);
			horizontalMenu1.Items.Add(attackButton);
			horizontalMenu1.Items.Add(assistButton);
			horizontalMenu1.Items.Add(patrolButton);
			horizontalMenu1.Items.Add(buildButton);

			factoryButton = new MenuItem();
			factoryButton.Text = "Factory";
			factoryButton.Id = "factoryButton";

			mineButton = new MenuItem();
			mineButton.Text = "Mine";
			mineButton.Id = "mineButton";

			supermarketButton = new MenuItem();
			supermarketButton.Text = "Supermarket";
			supermarketButton.Id = "supermarketButton";

			buildMenu = new VerticalMenu();
			buildMenu.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			buildMenu.Visible = false;
			buildMenu.Margin = new Thickness(243, 0, 0, 21);
			buildMenu.Id = "buildMenu";
			buildMenu.Items.Add(factoryButton);
			buildMenu.Items.Add(mineButton);
			buildMenu.Items.Add(supermarketButton);

			
			Widgets.Add(horizontalMenu1);
			Widgets.Add(buildMenu);
		}

		
		public MenuItem moveButton;
		public MenuItem attackButton;
		public MenuItem assistButton;
		public MenuItem patrolButton;
		public MenuItem buildButton;
		public MenuItem factoryButton;
		public MenuItem mineButton;
		public MenuItem supermarketButton;
		public VerticalMenu buildMenu;
	}
}
