/* Generated by MyraPad at 4/13/2021 11:03:40 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;

#if MONOGAME || FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#elif STRIDE
using Stride.Core.Mathematics;
#else
using System.Drawing;
using System.Numerics;
#endif

namespace GMRTSClient.UI
{
	partial class GameUI: Panel
	{
		private void BuildUI()
		{
			MoveButton = new ImageButton();
			MoveButton.Image = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("buttonassets/move.png");
			MoveButton.PressedImage = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("buttonassets/movePressed.png");
			MoveButton.Toggleable = true;
			MoveButton.Id = "MoveButton";

			AttackButton = new ImageButton();
			AttackButton.Image = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("buttonassets/attack.png");
			AttackButton.PressedImage = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("buttonassets/attackPressed.png");
			AttackButton.Toggleable = true;
			AttackButton.GridColumn = 1;
			AttackButton.Id = "AttackButton";

			AssistButton = new ImageButton();
			AssistButton.Image = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("buttonassets/assist.png");
			AssistButton.PressedImage = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("buttonassets/assistPressed.png");
			AssistButton.Toggleable = true;
			AssistButton.GridRow = 1;
			AssistButton.Id = "AssistButton";

			PatrolButton = new ImageButton();
			PatrolButton.Image = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("buttonassets/patrol.png");
			PatrolButton.PressedImage = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("buttonassets/patrolPressed.png");
			PatrolButton.Toggleable = true;
			PatrolButton.GridColumn = 1;
			PatrolButton.GridRow = 1;
			PatrolButton.Id = "PatrolButton";

			var grid1 = new Grid();
			grid1.ShowGridLines = true;
			grid1.ColumnSpacing = 8;
			grid1.RowSpacing = 8;
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Left;
			grid1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			grid1.Widgets.Add(MoveButton);
			grid1.Widgets.Add(AttackButton);
			grid1.Widgets.Add(AssistButton);
			grid1.Widgets.Add(PatrolButton);

			BuildTankButton = new ImageButton();
			BuildTankButton.Image = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("unitassets/Tank.png");
			BuildTankButton.PressedImage = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("buttonassets/patrolPressed.png");
			BuildTankButton.MaxWidth = 100;
			BuildTankButton.MaxHeight = 100;
			BuildTankButton.Id = "BuildTankButton";

			BuildBuilderButton = new ImageButton();
			BuildBuilderButton.Image = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("unitassets/Builder.png");
			BuildBuilderButton.PressedImage = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("buttonassets/patrolPressed.png");
			BuildBuilderButton.MaxWidth = 100;
			BuildBuilderButton.MaxHeight = 100;
			BuildBuilderButton.GridColumn = 1;
			BuildBuilderButton.Id = "BuildBuilderButton";

			BuildFactoryButton = new ImageButton();
			BuildFactoryButton.Image = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("unitassets/Factory.png");
			BuildFactoryButton.PressedImage = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("buttonassets/patrolPressed.png");
			BuildFactoryButton.MaxWidth = 100;
			BuildFactoryButton.MaxHeight = 100;
			BuildFactoryButton.GridColumn = 2;
			BuildFactoryButton.Id = "BuildFactoryButton";

			BuildMarketButton = new ImageButton();
			BuildMarketButton.Image = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("unitassets/Market.png");
			BuildMarketButton.PressedImage = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("buttonassets/patrolPressed.png");
			BuildMarketButton.MaxWidth = 100;
			BuildMarketButton.MaxHeight = 100;
			BuildMarketButton.GridColumn = 3;
			BuildMarketButton.Id = "BuildMarketButton";

			BuildMineButton = new ImageButton();
			BuildMineButton.Image = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("unitassets/Mine.png");
			BuildMineButton.PressedImage = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("buttonassets/patrolPressed.png");
			BuildMineButton.MaxWidth = 100;
			BuildMineButton.MaxHeight = 100;
			BuildMineButton.GridColumn = 4;
			BuildMineButton.Id = "BuildMineButton";

			BuildGrid = new Grid();
			BuildGrid.ShowGridLines = true;
			BuildGrid.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 100,
			});
			BuildGrid.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 100,
			});
			BuildGrid.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 100,
			});
			BuildGrid.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 100,
			});
			BuildGrid.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 100,
			});
			BuildGrid.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 100,
			});
			BuildGrid.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 100,
			});
			BuildGrid.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 100,
			});
			BuildGrid.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 100,
			});
			BuildGrid.CanSelectNothing = true;
			BuildGrid.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			BuildGrid.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			BuildGrid.Margin = new Thickness(0, 0, 0, 20);
			BuildGrid.Id = "BuildGrid";
			BuildGrid.Widgets.Add(BuildTankButton);
			BuildGrid.Widgets.Add(BuildBuilderButton);
			BuildGrid.Widgets.Add(BuildFactoryButton);
			BuildGrid.Widgets.Add(BuildMarketButton);
			BuildGrid.Widgets.Add(BuildMineButton);

			var horizontalSlider1 = new HorizontalSlider();
			horizontalSlider1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			horizontalSlider1.Width = 700;
			horizontalSlider1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;

			MineralLabel = new Label();
			MineralLabel.Text = "Minerals:";
			MineralLabel.Id = "MineralLabel";

			GoldLabel = new Label();
			GoldLabel.Text = "Gold:";
			GoldLabel.GridRow = 1;
			GoldLabel.Id = "GoldLabel";

			FPSLabel = new Label();
			FPSLabel.Text = "FPS: ";
			FPSLabel.GridRow = 2;
			FPSLabel.Id = "FPSLabel";



			var grid2 = new Grid();
			grid2.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
				Value = 100,
			});
			grid2.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
				Value = 100,
			});
			grid2.Widgets.Add(MineralLabel);
			grid2.Widgets.Add(GoldLabel);
			grid2.Widgets.Add(FPSLabel);

			
			Widgets.Add(grid1);
			Widgets.Add(BuildGrid);
			Widgets.Add(horizontalSlider1);
			Widgets.Add(grid2);
		}

		public Label FPSLabel;
		public ImageButton MoveButton;
		public ImageButton AttackButton;
		public ImageButton AssistButton;
		public ImageButton PatrolButton;
		public ImageButton BuildTankButton;
		public ImageButton BuildBuilderButton;
		public ImageButton BuildFactoryButton;
		public ImageButton BuildMarketButton;
		public ImageButton BuildMineButton;
		public Grid BuildGrid;
		public Label MineralLabel;
		public Label GoldLabel;
	}
}
