/* Generated by MyraPad at 3/28/2021 7:30:23 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;

#if MONOGAME || FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#elif STRIDE
using Stride.Core.Mathematics;
#else
using System.Drawing;
using System.Numerics;
#endif

namespace GMRTSClient.UI
{
	partial class GameUI: Panel
	{
		private void BuildUI()
		{
			MoveButton = new ImageButton();
			MoveButton.Image = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("buttonassets/move.png");
			MoveButton.PressedImage = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("buttonassets/movePressed.png");
			MoveButton.Toggleable = true;
			MoveButton.Id = "MoveButton";

			AttackButton = new ImageButton();
			AttackButton.Image = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("buttonassets/attack.png");
			AttackButton.PressedImage = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("buttonassets/attackPressed.png");
			AttackButton.Toggleable = true;
			AttackButton.GridColumn = 1;
			AttackButton.Id = "AttackButton";

			AssistButton = new ImageButton();
			AssistButton.Image = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("buttonassets/assist.png");
			AssistButton.PressedImage = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("buttonassets/assistPressed.png");
			AssistButton.Toggleable = true;
			AssistButton.GridRow = 1;
			AssistButton.Id = "AssistButton";

			PatrolButton = new ImageButton();
			PatrolButton.Image = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("buttonassets/patrol.png");
			PatrolButton.PressedImage = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("buttonassets/patrolPressed.png");
			PatrolButton.Toggleable = true;
			PatrolButton.GridColumn = 1;
			PatrolButton.GridRow = 1;
			PatrolButton.Id = "PatrolButton";

			var grid1 = new Grid();
			grid1.ShowGridLines = true;
			grid1.ColumnSpacing = 8;
			grid1.RowSpacing = 8;
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Left;
			grid1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			grid1.Widgets.Add(MoveButton);
			grid1.Widgets.Add(AttackButton);
			grid1.Widgets.Add(AssistButton);
			grid1.Widgets.Add(PatrolButton);

			var imageButton1 = new ImageButton();
			imageButton1.Image = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("unitassets/Tank.png");
			imageButton1.PressedImage = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("buttonassets/patrolPressed.png");
			imageButton1.MaxWidth = 100;
			imageButton1.MaxHeight = 100;

			var imageButton2 = new ImageButton();
			imageButton2.Image = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("unitassets/Builder.png");
			imageButton2.PressedImage = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("buttonassets/patrolPressed.png");
			imageButton2.MaxWidth = 100;
			imageButton2.MaxHeight = 100;
			imageButton2.GridColumn = 1;

			var grid2 = new Grid();
			grid2.ShowGridLines = true;
			grid2.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 100,
			});
			grid2.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 100,
			});
			grid2.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 100,
			});
			grid2.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 100,
			});
			grid2.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 100,
			});
			grid2.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 100,
			});
			grid2.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 100,
			});
			grid2.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 100,
			});
			grid2.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 100,
			});
			grid2.CanSelectNothing = true;
			grid2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			grid2.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			grid2.Margin = new Thickness(0, 0, 0, 20);
			grid2.Widgets.Add(imageButton1);
			grid2.Widgets.Add(imageButton2);

			var horizontalSlider1 = new HorizontalSlider();
			horizontalSlider1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			horizontalSlider1.Width = 700;
			horizontalSlider1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;

			
			Widgets.Add(grid1);
			Widgets.Add(grid2);
			Widgets.Add(horizontalSlider1);
		}

		
		public ImageButton MoveButton;
		public ImageButton AttackButton;
		public ImageButton AssistButton;
		public ImageButton PatrolButton;
	}
}
